build.sbt
project/plugins.sbt

Yaayyy! All you need to do is add a credentials file to `~/.ivy2/.sbtcredentials` that looks like:
```
realm=Spark Packages API
host=spark-packages.org
user=holdenk
password=$GITHUB_PERSONAL_ACCESS_TOKEN
```
Replace `$GITHUB_PERSONAL_ACCESS_TOKEN` with a personal access token with `read:org` scope. How to generate one is documented [here](https://help.github.com/articles/creating-an-access-token-for-command-line-use/).
Once that's done, just run `sbt spPublish` and you're done!
Enjoy!

added sbt-spark-package support

---

src/main/scala/com/holdenkarau/spark/testing/StreamingSuiteBase.scala

Fixes #2 by keeping the SparkContext open.   Looks to me like SharedSparkContext will stop it after all tests in the suite have run.

Fix NPE With Multiple Tests 

---

src/main/1.3/scala/com/holdenkarau/spark/testing/DataFrameSuiteBase.scala
src/test/1.3/scala/com/holdenkarau/spark/testing/MultipleDataFrameSuites.scala

Sql Context should be static as in Java unit tests non static variables
will be initialzed before every test case

Create static SqlContext at DataFrameSuiteBase

---

build.sbt
src/main/1.3/scala/com/holdenkarau/spark/testing/RDDGenerator.scala
src/test/1.3/scala/com/holdenkarau/spark/testing/SampleScalaCheckTest.scala

The current rdd generator generates locally and parallelizes, instead lets use the RandomRDD functionality in Spark to handle distributed test data generation (e.g. support property checking on datasets too large for a single machine).

Make rdd generator support large data sets

---

src/test/1.3/scala/com/holdenkarau/spark/testing/SampleScalaCheckTest.scala

Illustrate one of the ways we can specify the control sizes. We can also use resize.

Illustrate size control

---

src/main/1.3/scala/com/holdenkarau/spark/testing/StreamingSuiteBase.scala
src/test/1.3/scala/com/holdenkarau/spark/testing/SampleStreamingTest.scala

https://github.com/holdenk/spark-testing-base/issues/59
I think it's more logical that the number of batches = length of input size

Set number of batches to length of input list

---

src/main/1.5/scala/com/holdenkarau/spark/testing/SharedSparkContext.scala
src/main/resources/log4j.properties

Set log level in this log4.properties file instead of calling sparkContext.setLogLevel
This is compatible with all spark versions

Add Log4j properties file

---

src/main/1.3/scala/com/holdenkarau/spark/testing/LocalSparkContext.scala
src/main/1.3/scala/org/apache/spark/SparkUtils.scala

https://github.com/holdenk/spark-testing-base/issues/13
I added a method in `LocalSparkContext` to clear LocalRootDirs. I think it's better to just leave it like this and give the user the flexibility to use it whenever he wants. For ex. if he wants to use it after each test case, just call it after each test case. What do you think ?

Add method to clearLocalRootDirs

---

python/sparktestingbase/__init__.py
python/sparktestingbase/streamingtestcase.py
python/sparktestingbase/testcase.py

I want to use SparkTestingBase with a new Python3 project, but there were two errors.
1. The only acceptable syntax for relative imports is _from .[module] import name_. All import forms not  starting with . are interpreted as absolute imports. (PEP 328 - https://www.python.org/dev/peps/pep-0328/)
2. The print statement becomes the print() function in Python 3.0. (PEP 3105 - https://www.python.org/dev/peps/pep-3105/)
This pull request fixes both of these.

Port to Python3

---

src/main/1.6/scala/com/holdenkarau/spark/testing/Prettify.scala
src/test/1.6/scala/com/holdenkarau/spark/testing/PrettifyTest.scala

When property for dataframe fails output is not very meaningful , ie.:`arg0 = [name: string, age: int]`.
Here is proposal implicit method which can be used by `forAll` method. It can be added to scope either by extending trait or by importing `Prettify` object.

Make output of check pretty for generated Dataframe.

---

build.sbt
mini-cross-build.pl

Hi there,
This is a proposal for release with Spark 1.6.2.
Can you create a branch named `release-v1.6.2_0.4.4` so that I can PR there? I currently do this PR on master.

Prepare for release v1.6.2 0.4.4

---

src/main/2.0/scala/com/holdenkarau/spark/testing/DataFrameSuiteBase.scala

The Spark 2.0 implementation does not set the warehouse directory. When running in windows, this resulted in the error:
```
java.lang.IllegalArgumentException: java.net.URISyntaxException: Relative path in absolute URI: file:D:/CURRENT_DIRECTORY/spark-warehouse
```
This implementation allows me to proceed, but it appears there's an existing order-of-execution bug to fix:
```
16/10/05 09:09:44 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/10/05 09:09:45 WARN SparkContext: Use an existing SparkContext, some configuration may not take effect.
Warehouse dir: C:\Users\USER_NAME\AppData\Local\Temp\spark-32dad1e2-1224-4f11-aa2f-1be5b85dd73b\wharehouse
16/10/05 09:09:45 WARN SparkSession$Builder: Use an existing …
```

Set the spark 2.0 warehouse directory

---

src/main/1.3/scala/com/holdenkarau/spark/testing/StreamingSuiteBase.scala
src/main/1.3/scala/com/holdenkarau/spark/testing/StreamingSuiteCommon.scala
src/test/1.3/scala/com/holdenkarau/spark/testing/SampleStreamingTest.scala

This PR covers the scenario where a `DStream` and a `RDD` are joined using `transform` operation. 
Unfortunately I wasn't able to follow `testOperation` convention, since Scala type erasure. New method changes the type of `input2` to `Seq[V]` and `operation` to `(DStream[U], RDD[V]) => DStream[W])`. However after type erasure those types are `Seq` and `Function2`, so compiler thinks that there is a collision on signatures.  
Suggested name for the new method is `testOperationWithRDD`.

Add support for DStream and RDD operations.

---

README.md
RELEASE_NOTES.md
src/main/1.3/scala/com/holdenkarau/spark/testing/DataframeGenerator.scala
src/test/1.3/scala/com/holdenkarau/spark/testing/SampleScalaCheckTest.scala
src/test/1.6/scala/com/holdenkarau/spark/testing/PrettifyTest.scala

This PR adds support for N-level deep custom ColumnGenerators which are StructTypes.  This allows users to specify generators for fields in StructTypes, which is quite useful for generating complex data types to test.
The changes are summarized here:
- Added a new type `ColumnGeneratorList`
- Changed the type of `userGenerators` to be `Any*`, from `ColumnGenerator*`
- Change private signatures to match the above
- Assert at runtime that the types of the `userGenerators` belong to `ColumnGenerator` or `ColumnGeneratorList`, otherwise throw an `UnsupportedOperationException`
- Added a test for `ColumnGeneratorList`
Comparing the difference between no generators specified for a `StructType` column and having generators specified via a `ColumnGeneratorList`, I have not noticed a performance …

Add support for N-level custom ColumnGenerators with StructTypes

---

README.md

Summary of changes:
* Fixed some whitespace
* Formatted the code blocks
* Reference the Maven repositories page because the Spark Packages page doesn't have any updates since version 1.6.0_0.3.3

Format the code and whitespace in the README

---

build.sbt
src/main/1.3/scala/com/holdenkarau/spark/testing/DataframeGenerator.scala
src/main/2.0/scala/com/holdenkarau/spark/testing/MLUserDefinedType.scala
src/main/pre-2.0/scala/com/holdenkarau/spark/testing/MLUserDefinedType.scala
src/test/2.0/scala/com/holdenkarau/spark/testing/MLScalaCheckTest.scala

Spark ML has a couple of UDTs for vectors and matrices; this PR adds support for generating `DataFrame` instances for schemas containing them.
I've done this by adding an extractor that's used in the `match` statement of `DataframeGenerator.getGenerator`, because this seemed like a relatively unobtrusive way of dealing with these types only being available in Spark ≥ 2.0, but if you'd like this done in a different way I'm happy to change it.

Add support for generating the Spark ML UDTs.

---

src/main/2.0/scala/com/holdenkarau/spark/testing/DataFrameSuiteBase.scala

The PR just adds a `def enableHiveSupport = true` in `DataFrameSuiteBaseLike` to be able to enable/disable hive support from the actual TestSuite.
We have a repository with 104 test suites using DataFrameSuiteBase but we never need the hive support which is always enabled in `DataFrameSuiteBase`. The whole test suite takes more than 10 minutes to run (when it doesn't crash because of some strange exceptions). With hive support disabled, the tests take less than 5 minutes and the strange exceptions are gone.

Add option to enable/disable hive support in DataFrameSuiteBase

---

python/sparktestingbase/test/simple_test.py
python/sparktestingbase/testcase.py

there is no function to compare two RDD in Pyspark, so I wrote a compareRDD function which is similar to it in Scala version

add assertRDDEquals method for python

---

.travis.yml
README.md
RELEASE_NOTES.md
build.sbt
python/setup.py
python/sparktestingbase/__init__.py
python/sparktestingbase/pathmagic.py
python/sparktestingbase/sqltestcase.py
python/sparktestingbase/streamingtestcase.py
python/sparktestingbase/test/simple_sql_test.py
python/sparktestingbase/test/simple_streaming_test.py
python/sparktestingbase/test/simple_test.py
python/sparktestingbase/testcase.py
sbt/sbt
src/main/1.3/java/com/holdenkarau/spark/testing/SharedJavaSparkContext.java
src/main/1.3/scala/com/holdenkarau/spark/testing/YARNCluster.scala
src/main/2.0/scala/com/holdenkarau/spark/testing/DataFrameSuiteBase.scala

To get the release ready perform some minor cleanups, pep8 fixes, and update the version strings.
Also change new version (Spark 2.1.1+) to use JDK8 since Spark is deprecating JDK7 support going forwards.

Minor cleanups & pep8 fixes

---

python/sparktestingbase/sqltestcase.py
python/sparktestingbase/test/simple_sql_test.py

assertDataFrameEqual testcase passes when one of the DataFrame is empty fixed.

Fixing assertDataFrameEqual and adding unit tests

---

src/main/1.3/scala/com/holdenkarau/spark/testing/StreamingSuiteCommon.scala

Logging for output size verification will now print output size and expected output size.

Loggin fix

---

.travis.yml

Ubuntu 12.04  is unmaintained since April of 2017. It also produces warning in Travis. This pull request upgrades Ubuntu to 16.04.

Upgrade Ubuntu version in build

---

build.sbt
core/src/main/2.0/scala/com/holdenkarau/spark/testing/JavaStreamingSuitebase.scala
core/src/main/2.0/scala/com/holdenkarau/spark/testing/JavaSuiteBase.scala
core/src/test/2.0/java/com/holdenkarau/spark/testing/SampleJavaStreamingTest.java
project/plugins.sbt

This PR updates Scalafix to a newer version, it additionally replaces `HashBag` sorting with manual Java-based sorting. While this is definitely a little less pretty it reduces our dependency on `multisets`, which is required to allow us to support Scala 2.13.

Update ScalaFix & Remove dependency on Multisets

---

src/main/2.0/scala/com/holdenkarau/spark/testing/receiver/InputStreamSuiteBase.scala
src/main/2.0/scala/com/holdenkarau/spark/testing/receiver/InputStreamTestingContext.scala
src/main/2.0/scala/com/holdenkarau/spark/testing/receiver/InputStreamVerifier.scala
src/main/2.0/scala/com/holdenkarau/spark/testing/receiver/TestResultNotifier.scala
src/main/2.0/scala/com/holdenkarau/spark/testing/receiver/package.scala
src/test/2.0/scala/com/holdenkarau/spark/testing/InputStreamTest.scala
src/test/2.0/scala/org/apache/spark/streaming/StreamingContextWithExtraInputStreamGenerators.scala

Provides support for testing  InputDStreams  via the following pattern:
- create a StreamingContext from the SparkContext 
provided by SharedSparkContext
- execute a user-provided code block that transforms the 
framework-provided StreamingContext into a DStream
- after waiting for a configurable interval for the aforementioned 
code block to begin processing, execute a second block of 
code that generates test data to be consumed by the InputDStream
under test.
- compare the items encountered in the DStream produced by 
the first code block to a user specified list of expected items.

Provide support for testing InputDStreams

---

core/src/main/2.0/scala/com/holdenkarau/spark/testing/DataFrameSuiteBase.scala
core/src/test/2.0/scala/com/holdenkarau/spark/testing/SampleDataFrameTest.scala

There is one major error when comparing with structs after 2f6259c424c659807acce175d757494353d3846c in which if the first struct is ok the rest of the test does not evaluate
New feature adding tolerance to collections

fix: [~] row comparer & add list aprox comparer
