holdenk/spark-testing-base

- build.sbt
- src/main/scala/com/holdenkarau/spark/testing/StreamingSuiteBase.scala
- src/test/scala/com/holdenkarau/spark/testing/SampleStreamingTest.scala
Added support for multisets when useSet==true, as in https://github.com/holdenk/spark-testing-base/issues/6
> issue #6: using multisets when useSet==true

- build.sbt
- pom.xml
- src/main/scala/com/holdenkarau/spark/testing/Utils.scala
- src/main/scala/org/apache/spark/streaming/kafka/KafkaTestUtils.scala
- src/test/scala/com/holdenkarau/spark/testing/kafka/KafkaTestUtilsTest.scala
Contribute embedded Kafka(and ZooKeeper) for unit tests in SparkStreaming(KafkaUtils.directStream etc.)
> Added embedded kafka and zookeeper for unit testing

- python/setup.py
corrected name of required lib
> py.test -> pytest

- python/sparktestingbase/test/helloworld_test.py
Added missing unittest2 import to the helloworld example
> Added missing unittest2 import to the helloworld example

- src/main/1.3/java/com/holdenkarau/spark/testing/SharedJavaSparkContext.java
- src/main/1.3/scala/com/holdenkarau/spark/testing/DataFrameSuiteBase.scala
- src/main/1.3/scala/com/holdenkarau/spark/testing/JavaDataFrameSuiteBase.scala
- src/test/1.3/java/com/holdenkarau/spark/testing/SampleJavaDataFrameTest.java
- src/test/1.3/scala/com/holdenkarau/spark/testing/SampleDataFrameTest.scala
> F#30 add java dataframe implementation

- src/main/1.3/scala/com/holdenkarau/spark/testing/StreamingSuiteBase.scala
- src/test/1.3/scala/com/holdenkarau/spark/testing/SampleStreamingTest.scala
https://github.com/holdenk/spark-testing-base/issues/36
> Use custom equality object at testOperation

- src/main/1.3/scala/com/holdenkarau/spark/testing/DataFrameSuiteBase.scala
- src/main/1.3/scala/com/holdenkarau/spark/testing/JavaDataFrameSuiteBase.scala
- src/main/1.3/scala/com/holdenkarau/spark/testing/JavaSuiteBase.scala
- src/main/1.3/scala/com/holdenkarau/spark/testing/TestSuite.scala
- src/main/1.6/scala/com/holdenkarau/spark/testing/DatasetSuiteBase.scala
- src/test/1.3/java/com/holdenkarau/spark/testing/SampleJavaDataFrameTest.java
- src/test/1.3/scala/com/holdenkarau/spark/testing/SampleDataFrameTest.scala
- src/test/1.6/scala/com/holdenkarau/spark/testing/SampleDatasetTest.scala
This will enable us to create custom assertion logic
> Separate assertion logic between java & scala

- src/main/1.3/scala/com/holdenkarau/spark/testing/DataframeGenerator.scala
- src/main/1.3/scala/com/holdenkarau/spark/testing/RDDGenerator.scala
- src/test/1.3/scala/com/holdenkarau/spark/testing/SampleScalaCheckTest.scala
> Create DataFrame Generator

- src/main/1.3/scala/com/holdenkarau/spark/testing/DataframeGenerator.scala
- src/test/1.3/scala/com/holdenkarau/spark/testing/SampleScalaCheckTest.scala
#56 
I think we can find better name for method `genDataFrameWithCustomFields`.
> Add specific columns generators at DataFrameGenerator

- src/main/1.3/scala/com/holdenkarau/spark/testing/DataFrameSuiteBase.scala
- src/main/1.3/scala/com/holdenkarau/spark/testing/DataframeGenerator.scala
- src/main/1.3/scala/com/holdenkarau/spark/testing/JavaRDDComparisons.scala
- src/main/1.3/scala/com/holdenkarau/spark/testing/JavaStreamingSuitebase.scala
- src/main/1.3/scala/com/holdenkarau/spark/testing/RDDComparisons.scala
- src/main/1.3/scala/com/holdenkarau/spark/testing/RDDGenerator.scala
- src/main/1.3/scala/com/holdenkarau/spark/testing/TestSuite.scala
- src/main/1.3/scala/com/holdenkarau/spark/testing/Utils.scala
- src/main/1.6/scala/com/holdenkarau/spark/testing/DatasetGenerator.scala
- src/main/1.6/scala/com/holdenkarau/spark/testing/DatasetSuiteBase.scala
- src/test/1.3/java/com/holdenkarau/spark/testing/SampleJavaDataFrameTest.java
- src/test/1.3/java/com/holdenkarau/spark/testing/SampleJavaRDDTest.java
- src/test/1.3/scala/com/holdenkarau/spark/testing/SampleDataFrameTest.scala
- src/test/1.3/scala/com/holdenkarau/spark/testing/SampleRDDTest.scala
- src/test/1.3/scala/com/holdenkarau/spark/testing/SampleScalaCheckTest.scala
- src/test/1.6/java/com/holdenkarau/spark/testing/SampleJavaDatasetTest.java
- src/test/1.6/scala/com/holdenkarau/spark/testing/SampleDatasetTest.scala
> ADD RDDComparison Java support and unify all assert methods' names to use assert...Equals

- src/main/1.3/scala/com/holdenkarau/spark/testing/DataframeGenerator.scala
- src/test/1.3/scala/com/holdenkarau/spark/testing/SampleScalaCheckTest.scala
> F#82 add struct type data frame generation

- src/main/1.3/scala/com/holdenkarau/spark/testing/StreamingActionBase.scala
- src/main/1.3/scala/com/holdenkarau/spark/testing/StreamingSuiteBase.scala
- src/test/1.3/scala/com/holdenkarau/spark/testing/SampleStreamingActionTest.scala
- src/test/1.3/scala/com/holdenkarau/spark/testing/SampleStreamingTest.scala
> Remove explicit inheriting of FunSuite in StreamingSuite helpers

- src/main/1.3/scala/com/holdenkarau/spark/testing/DataFrameSuiteBase.scala
- src/test/1.3/scala/com/holdenkarau/spark/testing/SampleDataFrameTest.scala
- src/test/1.6/scala/com/holdenkarau/spark/testing/SampleDatasetTest.scala
https://github.com/holdenk/spark-testing-base/issues/106
> Define sqlContext as lazy val instead of def

- src/test/1.4/scala/com/holdenkarau/spark/testing/kafka/KafkaTestUtilsTest.scala
Closing Kafka consumer resolve throwing this exception multiple times during build
```
WARN ClientCnxn: Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
```
> Shutdown Kafka consumer after receiving message

- src/main/1.3/scala/com/holdenkarau/spark/testing/DataFrameSuiteBase.scala
- src/main/1.3/scala/com/holdenkarau/spark/testing/JavaRDDComparisons.scala
- src/main/1.3/scala/com/holdenkarau/spark/testing/RDDComparisons.scala
- src/main/1.3/scala/com/holdenkarau/spark/testing/TestSuite.scala
- src/main/1.6/scala/com/holdenkarau/spark/testing/DatasetSuiteBase.scala
- src/test/1.3/java/com/holdenkarau/spark/testing/SampleJavaRDDTest.java
- src/test/1.3/scala/com/holdenkarau/spark/testing/HDFSClusterTest.scala
- src/test/1.3/scala/com/holdenkarau/spark/testing/MultipleDataFrameSuites.scala
- src/test/1.3/scala/com/holdenkarau/spark/testing/SampleDataFrameTest.scala
- src/test/1.3/scala/com/holdenkarau/spark/testing/SampleRDDTest.scala
- src/test/1.3/scala/com/holdenkarau/spark/testing/SampleScalaCheckTest.scala
- src/test/1.6/scala/com/holdenkarau/spark/testing/SampleDatasetTest.scala
> F#108 use suite instead of fun suite

- src/test/1.3/scala/com/holdenkarau/spark/testing/SampleScalaCheckTest.scala
> Test that two evaluations of dataframe gives the same result.

- src/main/1.6/scala/com/holdenkarau/spark/testing/Prettify.scala
- src/test/1.6/scala/com/holdenkarau/spark/testing/PrettifyTest.scala
Like #118 . This time for RDDs and Datasets.
> Make output of check pretty for generated RDD and Dataset.

- build.sbt
- mini-cross-build.pl
> Update spark version to 2.0.1

- project/build.properties
In order to get deterministic and reproducible builds.
> Add build.properties with SBT version

- .travis.yml
- python/sparktestingbase/utils.py
- src/test/1.3/scala/com/holdenkarau/spark/testing/UtilsTest.scala
TODO: figure out why coverage is only reporting for python
> [WIP]Improve test coverage again

- .travis.yml
- build.sbt
- src/main/1.3/scala/com/holdenkarau/spark/testing/PerTestSparkContext.scala
- src/main/2.0/scala/com/holdenkarau/spark/testing/DataFrameSuiteBase.scala
- src/test/2.0/scala/com/holdenkarau/spark/testing/PerTestSparkContextTest.scala
Attempt to cleanup some non-built files since we are building 2.1 in CI
Add a Spark 2.0+ specific test
> Improve coverage of Scala tests

- build.sbt
- mini-cross-build.pl
- project/build.properties
Update for Spark 2.1.1 release.
Moreover,
* Update sbt to 0.13.15
* Update scala 2.11 to 2.11.11
> Update Spark version to 2.1.1

- .travis.yml
- RELEASE_NOTES.md
- build.sbt
- mini-cross-build.pl
- python/setup.py
- python/sparktestingbase/streamingtestcase.py
- src/main/1.3-only/scala/com/holdenkarau/spark/testing/LocalSparkContext.scala
- src/main/1.3/scala/com/holdenkarau/spark/testing/YARNCluster.scala
- src/main/1.4/scala/com/holdenkarau/spark/testing/LocalSparkContext.scala
- src/main/kafka/scala/org/apache/spark/streaming/kafka/KafkaTestUtils.scala
- src/test/1.3/scala/com/holdenkarau/spark/testing/SampleRDDTest.scala
- src/test/1.6/scala/com/holdenkarau/spark/testing/YARNClusterTest.scala
Add Spark 2.2.0 support and bump version to 0.7.1.
> Add Spark 2.2.0 support

- .travis.yml
- RELEASE_NOTES.md
- build.sbt
- src/main/1.3/scala/com/holdenkarau/spark/testing/YARNCluster.scala
The new travis infra isn't super happy -- its possible to the healthcheck was getting in the way. Disabled the healthcheck for disk space in the YARN cluster test and upgrade to more recent hadoop deps.
> Try and improve yarn cluster handling since its failing in travis

- README.md
- RELEASE_NOTES.md
Hi! I have noticed that  README.md's version is outdated so I updated it. Fixed some typos too :)
> Updates version on README.md to 0.7.4

- .travis.yml
- RELEASE_NOTES.md
- build.sbt
- mini-cross-build.pl
- python/setup.py
- Bumped version to 0.8.1
- Updated Hadoop libraries to 2.8.3
> Added support for Spark 2.2.1

- src/main/2.0/scala/com/holdenkarau/spark/testing/DataFrameSuiteBase.scala
- src/main/pre-2.0/scala/com/holdenkarau/spark/testing/DataFrameSuiteBase.scala
- src/test/1.3/scala/com/holdenkarau/spark/testing/SampleDataFrameTest.scala
- src/test/1.6/java/com/holdenkarau/spark/testing/SampleJavaDatasetTest.java
- src/test/1.6/scala/com/holdenkarau/spark/testing/SampleDatasetTest.scala
- src/test/pre-2.0/java/com/holdenkarau/spark/testing/SampleJavaDataFrameTest.java
Addition for tolerance of timestamps. The timestamp tolerance is in milliseconds.
> Timestamp Tolerance

- .travis.yml
- python/sparktestingbase/sqltestcase.py
- python/sparktestingbase/test/helloworld_test.py
- python/sparktestingbase/test/reuse_spark_context_test.py
- python/sparktestingbase/test/simple_sql_test.py
- python/sparktestingbase/test/simple_test.py
pep8 is old skool now, lets be new skool.
> Switch from pep8 to pycodestyle and fix the new issues

- core/src/main/2.0/scala/com/holdenkarau/spark/testing/DataFrameSuiteBase.scala
- core/src/test/2.0/scala/com/holdenkarau/spark/testing/SampleDataFrameTest.scala
Alternative to #319 that preserves the current semantics
Fixes #318
The two issues being addressed in this PR are:
1. When a row is in one DataFrame but not in the other one, either `expectedCol` or `actualCol` will be null and consequently the filter `col(expectedCol) =!= col(actualCol)` will return null and the missing row is incorrectly filtered out from the mismatched rows, making the assertion to pass when it shouldn't.
2. When both DataFrames have a common row with a field null, the full join using columns will not match them. They currently don't appear in the mismatched rows, but for the wrong reason, i.e. the bug in point 1, which once fixed this one starts occurring.
These issues are fixed in this PR by using the null-safe equality in both situations.
> Fix assertDataFrameNoOrderEquals with nulls

- core/src/main/1.3/scala/com/holdenkarau/spark/testing/DataframeGenerator.scala
- core/src/test/1.3/scala/com/holdenkarau/spark/testing/SampleScalaCheckTest.scala
Add support for `DecimalType` in `DataframeGenerator` which respects the precision and scale of the type.
> Support DecimalType in DataframeGenerator

- .github/workflows/github-actions-basic.yml
- build.sbt
Reverts holdenk/spark-testing-base#380
> Revert "Adding support for JDK 17"
